config/routes.rb
Rails.application.routes.draw do
  resources :color_palettes do
    scope module: :color_palettes do
      resources :colors, only: [:create, :update, :destroy] do
        scope module: :colors do
          resources :positions, only: [:create]
        end
      end
      resource :previews, only: [:show], path: "preview"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "color_palettes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/color.rb
class Color < ApplicationRecord
  belongs_to :color_palette
  acts_as_list scope: :color_palette

  after_create_commit :broadcast_new_color
  after_destroy_commit :broadcast_remove_color
  #after_update_commit :broadcast_replace_color
private
  def broadcast_new_color
    broadcast_append_to(color_palette, target: "color-palette", partial: "color_palettes/color",
      locals: { color: self })
  end

  def broadcast_remove_color
    broadcast_remove_to(color_palette, target: ActionView::RecordIdentifier.dom_id(self))
  end

  # def broadcast_replace_color
  #   broadcast_replace_to(color_palette, target: ActionView::RecordIdentifier.dom_id(self), partial: "color_palettes/color",
  #     locals: { color: self })
  # end
end

app/models/color_palette.rb
class ColorPalette < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :colors

  def header_color
    colors.find_by(category: "Header")&.hex || colors.find_by(position: 1)&.hex || "black"
  end

  def background_color
    colors.find_by(category: "Background")&.hex || colors.find_by(position: 2)&.hex || "white"
  end

  def paragraph_color
    colors.find_by(category: "Paragraph")&.hex || colors.find_by(position: 3)&.hex || "gray"
  end

  def button_background_color
    colors.find_by(category: "Button Background")&.hex || colors.find_by(position: 4)&.hex || "black"
  end

  def button_text_color
    colors.find_by(category: "Button Text")&.hex || colors.find_by(position: 2)&.hex || "white"
  end
end

app/models/color_pallete.rb
class ColorPallete < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :colors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/color_palettes/base_controller.rb
module ColorPalettes
  class BaseController < ApplicationController
    before_action :set_color_palette
  
  private
    def set_color_palette
      @color_palette = ColorPalette.friendly.find(params[:color_palette_id])
    end
  end
end

app/controllers/color_palettes/colors/positions_controller.rb
module ColorPalettes
  module Colors
    class PositionsController < ApplicationController
      before_action :set_color_palette, :set_color
      def create
        @color.insert_at(params[:position]) if params[:position].present?
        head :ok
      end
    private
      def set_color_palette
        @color_palette = ColorPalette.friendly.find(params[:color_palette_id])
      end

      def set_color
        @color = @color_palette.colors.find(params[:color_id])
      end
    end
  end
end

app/controllers/color_palettes/colors_controller.rb
module ColorPalettes
  class ColorsController < BaseController
    before_action :set_color, only: [:update, :destroy]
    def create
      @color_palette.colors.create(color_params)
      head :ok
    end

    def update
      @color.update(color_params)
      head :ok
    end

    def destroy
      @color.destroy!
      head :ok
    end
  private
    def set_color
      @color = @color_palette.colors.find(params[:id])
    end
    
    def color_params
      params.expect(color: [:hex, :category])
    end
  end
end

app/controllers/color_palettes/previews_controller.rb
module ColorPalettes
  class PreviewsController < BaseController
    def show
    end
  end
end

app/controllers/color_palettes_controller.rb
class ColorPalettesController < ApplicationController
  before_action :set_color_palette, only: %i[ show edit update destroy ]

  # GET /color_palettes or /color_palettes.json
  def index
    @color_palettes = ColorPalette.all
  end

  # GET /color_palettes/1 or /color_palettes/1.json
  def show
  end

  # GET /color_palettes/new
  def new
    @color_palette = ColorPalette.new
  end

  # GET /color_palettes/1/edit
  def edit
  end

  # POST /color_palettes or /color_palettes.json
  def create
    @color_palette = ColorPalette.new(color_palette_params)

    respond_to do |format|
      if @color_palette.save
        format.html { redirect_to @color_palette, notice: "Color palette was successfully created." }
        format.json { render :show, status: :created, location: @color_palette }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @color_palette.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /color_palettes/1 or /color_palettes/1.json
  def update
    respond_to do |format|
      if @color_palette.update(color_palette_params)
        format.html { redirect_to @color_palette, notice: "Color palette was successfully updated.", status: :see_other }
        format.json { render :show, status: :ok, location: @color_palette }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @color_palette.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /color_palettes/1 or /color_palettes/1.json
  def destroy
    @color_palette.destroy!

    respond_to do |format|
      format.html { redirect_to color_palettes_path, notice: "Color palette was successfully destroyed.", status: :see_other }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color_palette
      @color_palette = ColorPalette.friendly.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def color_palette_params
      params.expect(color_palette: [ :name ])
    end
end

app/controllers/color_palletes/colors_controller.rb
module ColorPalletes
  class ColorsController < ApplicationController
    before_action :set_color_pallete
    before_action :set_color, only: [:destroy]
    def create
      @color_pallete.colors.create(color_params)
      head :ok
    end

    def destroy
      @color.destroy!
      head :ok
    end
  private
    def set_color_pallete
      @color_pallete = ColorPallete.friendly.find(params[:color_pallete_id])
    end

    def set_color
      @color = @color_pallete.colors.find(params[:id])
    end
    
    def color_params
      params.expect(color: [:hex])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/color_palettes/_color.html.erb
<div class="flex flex-col items-center gap-4 group min-h-[80vh]" id="<%= dom_id(color) %>" data-url="<%= color_palette_color_positions_path(color.color_palette, color) %>">
  <div class="w-40 h-[70vh]" style="background-color: <%= color.hex %>;">

  </div>
  <div class="flex flex-col gap-8 h-40 relative w-full">
    <div class="handle cursor-pointer mx-auto hidden group-hover:flex">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" class="w-5 hover:scale-105">
        <path d="M16.1924 5.65683C16.5829 5.2663 16.5829 4.63314 16.1924 4.24261L13.364 1.41419C12.5829 0.633139 11.3166 0.633137 10.5355 1.41419L7.70711 4.24261C7.31658 4.63314 7.31658 5.2663 7.70711 5.65683C8.09763 6.04735 8.73079 6.04735 9.12132 5.65683L11 3.77812V11.0503H3.72784L5.60655 9.17157C5.99707 8.78104 5.99707 8.14788 5.60655 7.75735C5.21602 7.36683 4.58286 7.36683 4.19234 7.75735L1.36391 10.5858C0.582863 11.3668 0.582859 12.6332 1.36391 13.4142L4.19234 16.2426C4.58286 16.6332 5.21603 16.6332 5.60655 16.2426C5.99707 15.8521 5.99707 15.219 5.60655 14.8284L3.8284 13.0503H11V20.2219L9.12132 18.3432C8.73079 17.9526 8.09763 17.9526 7.7071 18.3432C7.31658 18.7337 7.31658 19.3669 7.7071 19.7574L10.5355 22.5858C11.3166 23.3669 12.5829 23.3669 13.364 22.5858L16.1924 19.7574C16.5829 19.3669 16.5829 18.7337 16.1924 18.3432C15.8019 17.9526 15.1687 17.9526 14.7782 18.3432L13 20.1213V13.0503H20.071L18.2929 14.8284C17.9024 15.219 17.9024 15.8521 18.2929 16.2426C18.6834 16.6332 19.3166 16.6332 19.7071 16.2426L22.5355 13.4142C23.3166 12.6332 23.3166 11.3668 22.5355 10.5858L19.7071 7.75735C19.3166 7.36683 18.6834 7.36683 18.2929 7.75735C17.9024 8.14788 17.9024 8.78104 18.2929 9.17157L20.1716 11.0503H13V3.87867L14.7782 5.65683C15.1687 6.04735 15.8019 6.04735 16.1924 5.65683Z" fill="#0F0F0F"/>
      </svg>
    </div>

    <div class="w-full flex" data-controller="dropdown" data-action="click@window->dropdown#closeIfOutside">
      <%= link_to "#", data: { action: "dropdown#toggle" }, class: "mx-auto hidden group-hover:flex" do %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6 hover:scale-105">
          <path stroke-linecap="round" stroke-linejoin="round" d="M6.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM12.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0ZM18.75 12a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0Z" />
        </svg>
      <% end %>

      <div data-dropdown-target="menu" class="absolute bottom-0 left-24 h-64 w-56 bg-white rounded-lg shadow-lg border border-gray-200 flex flex-col hidden z-[123]">
        <div class="w-full flex" data-controller="modal">
          <%= link_to "Set preview category", "#", class: "w-full text-gray-900 p-3 hover:bg-gray-200 text-center text-sm", 
            data: { action: "modal-opener#open dropdown#close", modal_id: dom_id(color, "preview-category-modal") } %>
        </div>
        <%= link_to "Remove color", color_palette_color_path(color.color_palette, color), data: { turbo_method: :delete }, class: "text-gray-900 mt-auto p-3 hover:bg-gray-200 hover:text-red-500 text-center text-sm" %>
      </div>
    </div>
  </div>
</div>

<%= render "color_palettes/preview_category_modal", color: color %>

app/views/color_palettes/_color_palette.html.erb
<div id="<%= dom_id color_palette %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Name:</strong>
    <%= color_palette.name %>
  </div>
</div>

app/views/color_palettes/_form.html.erb
<%= form_with(model: color_palette, class: "contents") do |form| %>
  <% if color_palette.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(color_palette.errors.count, "error") %> prohibited this color_palette from being saved:</h2>

      <ul class="list-disc ml-6">
        <% color_palette.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": color_palette.errors[:name].none?, "border-red-400 focus:outline-red-600": color_palette.errors[:name].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/color_palettes/_preview_category_modal.html.erb
<dialog id="<%= dom_id(color, "preview-category-modal") %>" class="mx-auto w-full h-full bg-transparent" data-modal-opener-target="modal"> 
  <div class="w-full h-full flex items-center justify-center">
    <div class="max-w-2xl w-full h-[40vh] rounded-lg bg-white z-[555] p-4 flex flex-col items-center" data-modal-content>
      <p class="text-3xl"> Set preview category </p>
      <p class="text-lg max-w-lg mx-auto text-center"> When viewing the preview for color palette you can choose which elements are using this color </p>
      <div class="w-full">
        <%= form_with url: color_palette_color_path(color.color_palette, color), model: color, data: { action: "submit->modal-opener#close" } do |f| %>
          <div class="flex flex-col gap-2 w-full">
            <%= f.label :category %>
            <%= f.select :category, options_for_select(["Header", "Paragraph", "Background", "Button Background", "Button Text"], color.category), { include_blank: true }, class: "w-full p-1 rounded-lg border-2 border-gray-200" %>
          </div>
          <div class="flex items-center gap-2 mt-4">
            <%= f.submit "Save changes", class: "py-2 px-3 rounded-lg bg-blue-500 text-blue-50 cursor-pointer" %>
            <%= link_to "Cancel", "#", data: { action: "modal-opener#close" }, class: "px-2 py-2 rounded-lg border-2 border-gray-900 text-gray-900" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</dialog>

app/views/color_palettes/edit.html.erb
<% content_for :title, "Editing color palette" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing color palette</h1>

  <%= render "form", color_palette: @color_palette %>

  <%= link_to "Show this color palette", @color_palette, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to color palettes", color_palettes_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/color_palettes/index.html.erb
<% content_for :title, "Color palettes" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Color palettes</h1>
    <%= link_to "New color palette", new_color_palette_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="color_palettes" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @color_palettes.any? %>
      <% @color_palettes.each do |color_palette| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render color_palette %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", color_palette, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_color_palette_path(color_palette), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", color_palette, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No color palettes found.</p>
    <% end %>
  </div>
</div>

app/views/color_palettes/new.html.erb
<% content_for :title, "New color palette" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New color palette</h1>

  <%= render "form", color_palette: @color_palette %>

  <%= link_to "Back to color palettes", color_palettes_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/color_palettes/previews/show.html.erb
<% content_for :title, "Preview #{@color_palette.name} Color Palette with UI" %>
<% @body_bg = @color_palette.background_color %>
<div class="w-full flex flex-col">
  <div class="flex mb-4">
    <%= link_to "Back to palette", @color_palette, class: "px-3 py-2 text-blue-50",  style: "background-color: #{@color_palette.button_background_color}; color: #{@color_palette.button_text_color}" %>
  </div>
  <div class="w-full min-h-[80vh] flex flex-col items-center px-8 lg:px-0 gap-4">
    <h1 class="text-5xl text-center font-semibold" style="color: <%= @color_palette.header_color %>"> Preview UI for <%= @color_palette.name %> </h1>
    <p class="max-w-2xl text-2xl text-center" style="color: <%= @color_palette.paragraph_color %>"> This is a cool way to test out your color scheme with a real UI web page </p>
    <%= link_to "#{@color_palette.name} is great!", "#", class: "px-3 py-2 rounded-lg text-lg", style: "background-color: #{@color_palette.button_background_color}; color: #{@color_palette.button_text_color}" %>
  </div>
</div>

app/views/color_palettes/show.html.erb
<% content_for :title, "#{@color_palette.name} Color Palette" %>
<%= turbo_stream_from @color_palette %>

<div class="w-full">
  <h1 class="font-bold text-4xl mb-4"> <%= @color_palette.name %> </h1>
  <div class="w-full flex items-center gap-4">
    <%= form_with url: color_palette_colors_path(@color_palette), model: @color_palette.colors.new do |f| %>
      <div class="flex items-center gap-4">
        <div class="flex flex-col gap-2">
          <%= f.label :hex, "Select a color" %>
          <%= f.color_field :hex %>
        </div>
        <%= f.submit "Add color", class: "px-3 py-2 rounded-lg bg-blue-500 text-blue-50 shadow-sm cursor-pointer" %>
      </div>
    <% end %>
    <%= link_to "Preview on UI", color_palette_previews_path(@color_palette), class: "px-3 py-2 rounded-lg bg-indigo-500 text-indigo-50 shadow-sm ml-auto" %>
  </div>

  <div class="min-h-[70vh] w-full mt-4 flex overflow-x-auto" id="color-palette" data-controller="sortable">
    <%= render(partial: "color", collection: @color_palette.colors.order(position: :asc)) if @color_palette.colors.reload.any? %>
  </div>

  <div class="flex gap-4 mt-8">
    <%= link_to "Edit this color palette", edit_color_palette_path(@color_palette), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= link_to "Back to color palettes", color_palettes_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
    <%= button_to "Destroy this color palette", @color_palette, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Color Palette Maker" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/color-picky.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/color-picky.svg">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-controller="modal-opener" data-action="click@window->modal-opener#closeIfOutside" style="background-color: <%= @body_bg || "white" %>">
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>